# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset= pd.read_excel("Folds5x2_pp.xlsx")
x= dataset.iloc[:, :-1].values
y= dataset.iloc[:, -1].values

In [4]:
print(x)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [5]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state=0)
y_train= y_train.reshape(len(y_train), 1)

### Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
sc_y= StandardScaler()
x_train= sc_x.fit_transform(x_train)
y_train= sc_y.fit_transform(y_train)
x_test= sc_x.transform(x_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [8]:
ann= tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

### Adding the second hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

### Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [12]:
ann.compile(optimizer= "adam", loss="mean_squared_error")

### Training the ANN on the Training set

In [13]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 0s 734us/step - loss: 0.6403
Epoch 2/100
240/240 [==============================] - 0s 726us/step - loss: 0.1912
Epoch 3/100
240/240 [==============================] - 0s 742us/step - loss: 0.1167
Epoch 4/100
240/240 [==============================] - 0s 730us/step - loss: 0.0987
Epoch 5/100
240/240 [==============================] - 0s 838us/step - loss: 0.0900
Epoch 6/100
240/240 [==============================] - 0s 784us/step - loss: 0.0844
Epoch 7/100
240/240 [==============================] - 0s 726us/step - loss: 0.0798
Epoch 8/100
240/240 [==============================] - 0s 751us/step - loss: 0.0763
Epoch 9/100
240/240 [==============================] - 0s 850us/step - loss: 0.0733
Epoch 10/100
240/240 [==============================] - 0s 700us/step - loss: 0.0708
Epoch 11/100
240/240 [==============================] - 0s 717us/step - loss: 0.0690
Epoch 12/100
240/240 [==============================] - 0s 842us/step - lo

240/240 [==============================] - 0s 1ms/step - loss: 0.0592
Epoch 98/100
240/240 [==============================] - 0s 713us/step - loss: 0.0593
Epoch 99/100
240/240 [==============================] - 0s 793us/step - loss: 0.0594
Epoch 100/100
240/240 [==============================] - 0s 688us/step - loss: 0.0590


## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [14]:
y_pred= ann.predict(x_test)
print(sc_y.inverse_transform(y_pred))

[[432.5884 ]
 [456.1355 ]
 [462.29303]
 ...
 [467.70157]
 [438.40277]
 [460.77475]]


In [15]:
print(y_test)

[431.23 460.01 461.14 ... 473.26 438.   463.28]


In [17]:
from sklearn.metrics import r2_score
r2_score(y_test, sc_y.inverse_transform(y_pred))

0.9448021545583257